### ISSUE TITLE
Remo spamming emails

### ISSUE THREAD

**Issue by flamingspaz** [mozilla/parsys#221] opened 2017-08-25 10:31 UTC
Remo is sending out 50+ of the same email

**Comment by flamingspaz** [comment] 2017-08-25 13:32
Most likely related to redis/celery timeouts, this was merged and should fix the issue:
https://github.com/mozilla/remo/commit/39b6e66f5f6a67bb776586d59f6ca96e77828484

@akatsoulas do we need to flush the task queue?

**Comment by akatsoulas** [comment] 2017-08-25 14:30
I don't believe so but let's keep an eye on how celery is going to behave after the recent change.

**Comment by MichaelKohler** [comment] 2017-08-25 15:27
What do you mean with "recent"? The same has happened this morning with the RoM end results.

**Comment by MichaelKohler** [comment] 2017-08-25 15:28
Eh sorry, nevermind me. Misread yousef's comment. Let's see

**Comment by akatsoulas** [comment] 2017-08-25 15:40
@MichaelKohler if you see any strange activity (eg multiple emails) can you post it here?

**Comment by MichaelKohler** [comment] 2017-08-25 15:43
I can create a Council voting to see what happens if that would help you.

**Comment by akatsoulas** [comment] 2017-08-25 16:05
Go for it.

**Comment by MichaelKohler** [comment] 2017-08-25 16:16
I've created a voting here: https://reps.mozilla.org/v/testing-spamming-remobot/
So far I've only received one email ("Cast the vote"). Let's see if the result mail is ok as well.

**Comment by Mte90** [comment] 2017-08-25 20:06
I received only 5 email that the vote was closed, better then the other day but in any case maybe too much XD

**Comment by MichaelKohler** [comment] 2017-08-25 20:48
![screen shot 2017-08-25 at 22 46 38](https://user-images.githubusercontent.com/330324/29732074-51506102-89e7-11e7-9055-3a582df58a8b.png)

@Mte90 I only received 4. But that might also be my spam stuff kicking in.

In any case, for the results email this doesn't seem to be fixed.

**Comment by akatsoulas** [comment] 2017-08-26 08:15
Thank you both for testing this. We will continue investigating this until it's resolved.

**Comment by ankitgadgil** [comment] 2017-09-01 15:40
This is still spamming, for https://reps.mozilla.org/v/budget-request-flore-allemandou-https-reps-mozilla-org-e-write-the-docs/ the remobot sent 82 emails to me.

**Comment by flamingspaz** [comment] 2017-09-01 15:51
Something is causing the worker to receive the task every hour from when it's created. The redis timeout is set to 5 days now, so there would be much less emails if that was the issue.

@akatsoulas could this be potentially timezone related? I can't see anything else that would cause an hourly task, beat only sends one out.

**Comment by Mte90** [comment] 2017-09-12 15:01
Happening right now with over 50 emails

**Comment by flamingspaz** [comment] 2017-09-13 13:58
@johngian any ideas here?

**Comment by Mte90** [comment] 2017-09-13 13:59
It is happened also today

**Comment by AlexLakatos** [comment] 2017-09-25 00:43
I got 150+ emails in the last 40 minutes. No sign of slowing down or stopping.
<img width="1064" alt="screen shot 2017-09-25 at 01 43 04" src="https://user-images.githubusercontent.com/690132/30788352-fa82a4c0-a192-11e7-82bb-f9934d8dd7ab.png">

**Comment by AlexLakatos** [comment] 2017-09-25 01:09
It stopped at 284 emails in 53 minutes.

**Comment by AlexLakatos** [comment] 2017-09-25 01:10
Started at 1 am in the morning for whoever was wondering

**Comment by hmitsch** [comment] 2017-09-25 01:15
It reached 170 mails for me. :-( 

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/869692/30788682-b2ab6828-a19f-11e7-8c60-5078ecdc562b.png">

**Comment by AlexLakatos** [comment] 2017-09-25 01:47
It's ok, I created this little filter for my inbox that is going to forward everything from ReMoBot here from now on. We'll all have advanced warning when it's happening next time. 😈

**Comment by nukeador** [comment] 2017-09-25 09:44
@AlexLakatos Note some remobot emails contain non-public information as mentor and Council member.

@hmitsch This has been bothering a lot of people for a few months now, can we find a solution even if it's a temporal one?

**Comment by flamingspaz** [comment] 2017-09-26 17:57
we pushed a fix today that we're 99.9% sure will fix the issue. i'll leave this open until we've confirmed.

**Comment by hmitsch** [comment] 2017-09-26 19:11
... and we will provide a Post Mortem to be more transparent on what caused the issue and why it took so long to identify it.

**Comment by MichaelKohler** [comment] 2017-09-26 20:34
First of all, thanks for your efforts! What does the "fix the issue" mean exactly? I've created two test votings and none of them sent *any* mails. No "cast your vote", no "results are in". Did you completely disable the emails?

**Comment by johngian** [comment] 2017-09-28 07:56
Hey @MichaelKohler what happened is the following:

* We found the issue that caused our background tasks to be spawned multiple times (aka email spamming).
* We fixed it
* We verified everything with a dummy test in order to avoid spamming everyone
* It worked

The problem you face is caused by AWS and should be fixed now. In fact we verified that voting emails are being sent. Can you also verify that?

We will post an in-depth post mortem of the bug we faced that caused the spamming incidents.

**Comment by MichaelKohler** [comment] 2017-09-28 12:21
I've tested it with a voting, the voting start mails were sent correctly. At the time the voting finished, we got 1 mail to the alias with the result. This seems all fine. I've waiting an hour to write this confirmation to make sure there is no other trigger, but doesn't look like it right now.

Thanks a lot for your efforts. <3 This can be closed!

**Closed as completed** 2017-09-28 13:21 UTC
Labels: [INFRASTRUCTURE]

**Comment by nukeador** [comment] 2017-09-28 14:55
Thanks for this.

**Comment by hmitsch** [comment] 2017-09-29 19:58
More info on the root cause: https://discourse.mozilla.org/t/reps-mozilla-org-email-spamming-incident/19707
